const SUCCESS_STATUS = 200;
const CREATED_STATUS = 201;
const NOT_FOUND_STATUS = 404;
const BAD_REQUEST_STATUS = 400;
const SERVER_ERROR_STATUS = 500;

const SERVER_ERROR_MESSAGE = 'Произошла ошибка на сервере';
const NOT_FOUND_USER_MESSAGE = 'Пользователь не найден';

export {
  SUCCESS_STATUS,
  CREATED_STATUS,
  NOT_FOUND_STATUS,
  BAD_REQUEST_STATUS,
  SERVER_ERROR_STATUS,
  SERVER_ERROR_MESSAGE,
  NOT_FOUND_USER_MESSAGE,
};
