const SUCCESS_STATUS = 200;
const CREATED_STATUS = 201;
const NOT_FOUND = 404;
const BAD_REQUEST_STATUS = 400;
const SERVER_ERROR_STATUS = 500;

export {
  SUCCESS_STATUS,
  CREATED_STATUS,
  NOT_FOUND,
  BAD_REQUEST_STATUS,
  SERVER_ERROR_STATUS,
};
